# Generated by Django 3.2.5 on 2021-08-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerfinder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
