# Generated by Django 3.2.5 on 2021-08-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerfinder', '0002_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyers',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lawyerfinder.lawyers')),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
